// app/components/Navbar.tsx
import React from "react";
import Link from "next/link";

const Navbar = () => {
  return (
    <>
      <div className="w-full h-20 bg-[rgb(99,168,163)] sticky top-0">
        <div className="container mx-auto px-4 h-full">
          <div className="flex justify-between items-center h-full">
            
            <div className="flex pb-5 pt-4">
              <img className=' h-20 w-64' src="logo1.png" alt="EPICS Logo" width="50"/>
              <div>
                <img className=' h-20 w-64' src="team-formation-text.png" alt="Team Formation Logo" width="100"/>
              </div>
            </div>

            <ul className="hidden md:flex gap-x-6 text-white">
              <li>
                <Link href="/sign-in">
                  <p>Sign In</p>
                </Link>
              </li>
              <li>
                <Link href="/project">
                    <p>Project</p>
                </Link>
                
              </li>
              <li>
                <Link href="/dashboard">
                  <p>Student Upload</p>
                </Link>
                
              </li>
              <li>
                <Link href="/display">
                    <p>Generate</p>
                </Link>
              </li>
              
            </ul>
          </div>
        </div>
      </div>
    </>
  );
};

export default Navbar;

// components/Navbar.vue
<template lang="pug">
  .sticky.top-0.p-4.z-10.flex.justify-between.items-center.bg-teal
    .flex
      img.h-20.w-64(
        alt="EPICS Logo" 
        src="/logo1.png" 
      )
      img.h-20.w-64(
        alt="Team Formation Logo" 
        src="/team-formation-text.png" 
      )
    .flex.text-xl.gap-x-6
      NuxtLink(to="/projects") Projects
      NuxtLink(to="/students") Students
      NuxtLink(to="/generate-teams") Generate Teams
      NuxtLink(to="/demographics") Demographics
      NuxtLink(to="/past-projects") Past Projects
      
    .centered-row.gap-4.ml-auto.mr-10
      NuxtLink(to="https://discord.gg/UyPg3ykKq3")
        img.size-8(
          alt="Discord Logo"
          src="/discord.svg"
        )
      NuxtLink(to="https://github.com/UTDallasEPICS/Teambuilder")
        img.size-8(
          alt="GitHub Logo"
          src="/github-mark.png"
        ) 
</template>
