// components/FileUploader.vue
<template lang="pug">
div
  button(style={marginLeft: '20px', marginTop: '50px'} class='border-solid border-8 p-1 border-transparent rounded-xl bg-[rgba(96,241,135,0.9)] text-xl' @click="handleClick")
    | Student List Upload
  input(type="file" @change="handleChange" ref="hiddenFileInput" style={display: 'none'})
</template>

<script setup lang="ts">
import { ref } from 'vue';

const hiddenFileInput = ref<HTMLInputElement | null>(null);

const handleClick = () => {
  hiddenFileInput.value?.click();
};

const handleChange = (event: Event) => {
  const fileUploaded = (event.target as HTMLInputElement).files?.[0];
  handleFile(fileUploaded!);
};

const handleFile = (file: File | null) => {
  // handle the file
};
</script>

<style scoped>
.border-solid {}
</style>

// Teambuilder/app/components/FileUploader.tsx
import {useRef} from 'react'

export const FileUploader = ({ handleFile }) => {
  
  // Create a reference to the hidden file input element
  const hiddenFileInput = useRef(null);

  // Programatically click the hidden file input element
  // when the Button component is clicked
  const handleClick = (event) => {
    hiddenFileInput.current.click();
  };
  // Call a function (passed as a prop from the parent component)
  // to handle the user-selected file
  const handleChange = (event) => {
    const fileUploaded = event.target.files[0];
    handleFile(fileUploaded);
  };

 return (
    <div>
      <button style={{marginLeft: '20px' , marginTop: '50px'}} className=' border-solid border-8 p-1 border-transparent rounded-xl bg-[rgba(96,241,135,0.9)] text-xl' onClick={handleClick}>
                Student List Upload
      </button>
      <input
        type="file"
        onChange={handleChange}
        ref={hiddenFileInput}
        style={{ display: "none" }} // Make the file input element invisible
      />

    </div>
  )
}

export default FileUploader
